### PR TITLE
Update MinIO Go SDK to v7.0.44

### PR DESCRIPTION
**Pull request by freix1**
Among other small bug fixes this update adds support for the `eu-south-2`, `eu-central-2`, `me-central-1`, `ap-southeast-3` AWS endpoints.

I have tested this update by creating a S3 bucket on the EU (Zurich) `eu-central-2` endpoint and being successfully able to store a backup to it.

Furthermore, I have also tried running the tests by replacing all occurrences of the image `offen/docker-volume-backup:${TEST_VERSION:-canary}` with my locally built image (I am not sure whether that is the correct approach). However, I got stuck on the `commands/run.sh` test case because of a reference to `/var/lib/docker/volumes/commands_archive/_data`. I cannot resolve this path on macOS and Windows (using WSL2 Ubuntu), which leads me to assume that the tests might need to be run on a Linux OS. Unfortunately, I currently do not have a Linux OS on hand, but I can set up a quick VM tomorrow and try running the tests again if need be.

This PR addresses the issue #166.

### CODE REVIEW

**Comment by m90** [comment]
> Unfortunately, I currently do not have a Linux OS on hand, but I can set up a quick VM tomorrow and try running the tests again if need be.

CircleCI can do this for us, we'll see if the test pass very soon.

**Review by m90 — APPROVED** [review]
Brilliant, thanks for taking care of updating and also testing this against live infrastructure.

**Comment by m90** [comment]
> Unfortunately, I currently do not have a Linux OS on hand, but I can set up a quick VM tomorrow and try running the tests again if need be.

For future reference, I usually build the image tagged `canary` myself and then run the tests, but then again I am on Linux which probably is an unfair advantage in this scenario. I don't really know how well the setup works on Mac or WSL. Pushing and having CircleCI run the tests should be a viable alternative in any case though.

**Comment by m90** [comment]
This is now released in `v2.22.2`. Thanks for your contribution :tophat:

**Comment by freix1** [comment]
> For future reference, I usually build the image tagged `canary` myself and then run the tests, but then again I am on Linux which probably is an unfair advantage in this scenario. I don't really know how well the setup works on Mac or WSL. Pushing and having CircleCI run the tests should be a viable alternative in any case though.

Thank you very much for the clarification. It definitely makes sense to just let CircleCI run the tests and thus avoid the trouble of having to deal with individual OS related problems.

I am very grateful for the speedy response and release as well!

**Pull request merged**
