### PR TITLE
Move cron scheduling inside application

### LINKED ISSUE #268: Consider using a dedicated cron package
The limitations of BusyBox's cron implementation when it comes to defining schedules crop up again and again e.g. #267 #185 #117

There seems to be a standalone apk package for cron https://pkgs.alpinelinux.org/package/edge/main/x86/apk-cron which seems lightweight enough to install it in the image if:
- it supports all syntax that is supported by BusyBox
- it adds missing features like `\` or `-`

Since this __the core feature__ of this image, possible incompatibilities should be scrutinized closely before actually implementing.

### PR DESCRIPTION
**Pull request by m90**
Closes #268

### CODE REVIEW

**Comment by m90** [comment]
@pixxon Just to give un update on the status of this: I did some minor tweaking in regards to error handling and logging and would think this is now ready to go from a code perspective.

As we're now having a long running process though, I'd still like to confirm this doesn't leak memory somehow, so I'll let the current state of this branch (`v2.37.0-alpha.3`) run on all of my setups and check memory usage over the course of a week. If this looks unsuspicous, I'd say let's ship it.

**Comment by pixxon** [comment]
Sounds great!

I am not familiar with golang, but maybe there are some tools to help finding memory leaks. ( In the c++ word, there are some great static analyzers that help, or even better are the memory sanitizers that check for addresses that were not freed properly. )

**Comment by m90** [comment]
The only way to really leak memory in Go is to have goroutines running that never return, meaning everything in their scope isn't possible to be garbage collected. I definitely managed to do this before, even when having static analysis look for such problems. I don't think it's likely here, but I'd feel safer if I've seen it running for a bit.

One simple thing we could do is print the numbers of Go routines from time to time to see if the number stays stable, but I guess I'll defer that until it looks like there really is a leak.

**Comment by m90** [comment]
I got nerd sniped and fired up [`pprof`](https://pkg.go.dev/net/http/pprof) which let me indeed finf a leak: the Docker client leaks a persistent HTTP connection when you don't call `Close` on the client object.

After doing this, the number of Goroutines seems stable when I run a per-minute schedule locally for ~15mins or so.

See 68ba6ce5a1c4523bde3035e415f7396bd90d54be as a fix

I'll push this as `v2.37.0-alpha.4` and deploy it.

**Comment by m90** [comment]
Seems the advice on closing it is right there in the docs https://pkg.go.dev/github.com/docker/docker/client#section-readme ....

**Pull request merged**
